name: Action_ref
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Display action ref
        run: echo "Action ref is ${{ github.action_ref }}"
