name: ARTIFACT
on: workflow_dispatch
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: set variable value

        run: |
          echo shamsoddin > variable.txt
          echo "name=variable.txt" >> "$GITHUB_ENV"

      - name: upload data on artifact
        uses: actions/upload-artifact@v3
        with:
          name: variable
          path: ${{ env.name }}
