on: workflow_dispatch
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout another repository
        uses: actions/checkout@v3
        with:
          repository: ${{ shamsoddin-mujawar }}/nodejs-updates




