name: COMPOSITE_ACTION
on: workflow_dispatch
jobs:
  FIRST-JOB:
    runs-on: ubuntu-latest
    steps:
      - id: comp
        uses: ./.github/actions/composite-action

      - name: print variable output value
        run: echo "output value is - ${{ steps.comp.outputs.result }}"

      - name: print github env var value
        run: echo " sum is - $sum"
