name: CRON_JOB
on: workflow_dispatch
#   schedule:
#     - cron: '*/5 * * * *'
env:
  TZ: Asia/Kolkata
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: running 
      run: echo "Hello Shamsoddin..."
