name: CUSTOM_VARIABLE
on: workflow_dispatch
jobs:
  First-job:
    runs-on: ubuntu-latest
    env: 
      MY_VAR: "World"
    steps:
      - name: print actor name
        run: echo "Env variable name is - $MY_VAR"

      - name: accessing using expression
        run: echo "variable - ${{ env.MY_VAR }}

  Second-job:
    needs: First-job
    runs-on: ubuntu-latest
    steps:
    - name: print env
      run: echo "Env variable name is - $MY_VAR"
        
