name: GITHUB_OUTPUT
on: workflow_dispatch
jobs:
  First:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ steps.custom_step.outputs.result }}
    steps:
      - name: set output
        id: out_name
        run: |
          echo "sum=None" >> "$GITHUB_OUTPUT"

      - name: print output
        run: |
          echo " ${{ steps.out_name.outputs.sum }}
  
  Second:
    runs-on: ubuntu-latest
    needs: First
    steps:
      - name: printing jobs output value set in job1
        run: echo "output value is - ${{needs.First.outputs.out}}"
