name: INBUILT_VARIABLE
on: workflow_dispatch
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: print env variable
        run: echo "GitHub default GITHUB_ACTOR variable value is - $GITHUB_ACTOR"
