name: JOB_CONDITION
on: workflow_dispatch
jobs:
 test2:
  if: github.repository == 'shamsoddin-mujawar/GHA_pra'  
  runs-on: ubuntu-latest
  steps:
    - name: run command
    - run: echo "executing job condition "
