name: JOB_CONDITION
on: workflow_dispatch
jobs:
  test1:
    if: github.repository == 'shamsoddin-mujawar/GHA-practice'
    runs-on: ubuntu-latest
    steps:
      - name: run command
        run: echo "executing job condition 

  test2:
    needs: test1
    runs-on: ubuntu-latest
    steps:
      - name: second job
        run: echo 'second job'

