name: PUSH_JOB
on:
  push:
    branches:
      - 'main'
      - 'test'
    paths:
      - '**.py'
jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: push job
        run: echo "hello job"
