name: CODE_CHECKOUT
on: workflow_dispatch
jobs:
  First:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: checkout other repo code
        uses: actions/checkout@v4
        with:
          repository: shamsoddin-mujawar/GHA-actions-python
          ref: main
          path: GHA-actions-python

