name: CODE_CHECKOUT
on: workflow_dispatch
jobs:
  First:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          # path: GHA-practice
      
      - name: working dir
        run: pwd

  Second:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
         repository: shamsoddin-mujawar/GHA-actions-python
         ref: main
         path: GHA-actions-python
        
      - name: working dir
        run: pwd

