name: SECRETS_AND_VARIABLES
on: workflow_dispatch
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: print repository secrets
        run: |
          echo "secret USERNAME value is - ${{ secrets.USERNAME }}"

      - name: print environment secrets
        run: |
          echo " env secret NAME value is - ${{ Test.ENV_SEC_NAME }}"
