name: SECRETS_AND_VARIABLES
on: workflow_dispatch
jobs:
  REPO-SECRETS:
    runs-on: ubuntu-latest
    steps:
      - name: print repository secrets
        run: |
          echo "secret USERNAME value is - ${{ secrets.USERNAME }}"

  ENV-SECRET:
    environment: Test
    env:
        NAME: ${{secrets.ENV_SEC_NAME}}
    runs-on: ubuntu-latest
    steps:
      - name: print environment secrets
        run: |
          echo " env secret NAME value is - $SEC_NAME
