name: SECRETS_AND_VARIABLES
on: workflow_dispatch
jobs:
  REPO-SECRETS-AND-VARIABLES:
    runs-on: ubuntu-latest
    steps:
      - name: print repository secrets
        run: |
          echo "Repository secret USERNAME value is - ${{ secrets.USERNAME }}"

      - name: print repository variable
        run: |
          echo "Repository variable value is - ${{ vars.REPO_PASS_VAR }}"

  ENV-SECRETS-AND-VARIABLES:
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: print environment secrets
        run: |
          echo "env secret SEC_NAME value is - ${{secrets.ENV_SEC_NAME}}"

      - name: print environment variable
        run: |
          echo "env variable is - ${{ vars.ENV_PASS_VAR }}"
