name: SECRETS_AND_VARIABLES
on: workflow_dispatch
jobs: 
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: print repo secrets
        run: |
          echo "secret username is - $secrets.USERNAME"
          
      - name: print repo variable
        run: |
          echo "repo env USER is - $USER"
