name: FIRST_TEST_WORKFLOWS 
on: workflow_dispatch   
jobs: 
  First-job: 
    runs-on: ubuntu-latest 
    steps: 
      - name: print hello 
        run: |
          echo "Hello world!"
          
          echo "GHA - ${GITHUB_SHA}"
          
      - name: custom action
        uses: docker-action/action@v1
        with:
          image: nginx

      - name: print
        run: echo "hello"
