name: WORKFLOWS_DISPATCH_PASS_INPUTS
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      name:
        description: "name"
        required: false
        type: string
jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: printing values
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Name : $NAME"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          NAME: ${{ inputs.name }}



